version: '3'
services:
  db:
    image: postgres:12.2-alpine
    ports:
      - 5455:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=app
  db_1:
    image: postgres:12.2-alpine
    ports:
      - 5458:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=go